[http.middlewares]
  [http.middlewares.middlewares-rate-limit]
    [http.middlewares.middlewares-rate-limit.rateLimit]
      average = 100
      burst = 50

# Available Header Options:
#####https://github.com/unrolled/secure#available-options
#####https://docs.traefik.io/middlewares/headers/
# A great resource for these headers is your preferred browser's docs. Firefox: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
# https://developers.google.com/search/reference/robots_meta_tag
# https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Clickjacking_Defense_Cheat_Sheet.md
# CSP for VNC: https://github.com/cockpit-project/cockpit/pull/5932
# Check headers here, don't include OAuth when checking headers, otherwise you are checking google's headers: https://securityheaders.com
# or check them here: https://observatory.mozilla.org/

# CAUTION: Any headers defined in docker-compose (yml) will OVERWRITE ALL of the headers defined below.

  [http.middlewares.middlewares-secure-headers]
    [http.middlewares.middlewares-secure-headers.headers]
      accessControlAllowMethods = ["GET", "OPTIONS", "PUT"]
      accessControlAllowOriginList = ["https://example.com","https://google.com","http://example.co.in", "http://localhost", "https://example.in", "https://exit.example.in"]
      accessControlMaxAge = 100
      hostsProxyHeaders = ["X-Forwarded-Host"]
      sslRedirect = true
      stsSeconds = 63072000
      stsIncludeSubdomains = true
      stsPreload = true
      forceSTSHeader = true
#      frameDeny = true #overwritten by customFrameOptionsValue
      customFrameOptionsValue = "allow-from https:example.com" #CSP takes care of this but may be needed for organizr.
      contentTypeNosniff = false
      browserXssFilter = false
#      sslForceHost = true # add sslHost and all of the
#      sslHost = "example.com"
#      referrerPolicy = "same-origin"
      referrerPolicy = "origin-when-cross-origin"
#      Setting contentSecurityPolicy is more secure but it can break things. Proper auth will reduce the risk.
#      the below line also breaks some apps due to 'none' - sonarr, radarr, etc.
#      contentSecurityPolicy = "frame-ancestors '*.biso.work:*';object-src 'none';script-src 'none';"
#      featurePolicy = "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
      [http.middlewares.middlewares-secure-headers.headers.customResponseHeaders]
        X-Robots-Tag = "none,noarchive,nosnippet,notranslate,noimageindex"
        server = ""
#        X-Forwarded-Ssl=on
#        X-Forwarded-Port=443
#        X-Forwarded-Proto=https

#  [http.middlewares.middlewares-oauth]
#    [http.middlewares.middlewares-oauth.forwardAuth]
#      address = "http://oauth:4181" # Make sure you have the OAuth service in docker-compose.yml
#      trustForwardHeader = true
#      authResponseHeaders = ["X-Forwarded-User"]

  [http.middlewares.middlewares-basic-auth]
    [http.middlewares.middlewares-basic-auth.basicAuth]
      realm = "Traefik2 Basic Auth"
      usersFile = "/shared/.htpasswd" #be sure to mount the volume through docker-compose.yml


  [http.middlewares.cloudflare-ipwhitelist]
    [http.middlewares.cloudflare-ipwhitelist.ipWhiteList]
      sourceRange = [
        "173.245.48.0/20",
        "103.21.244.0/22",
        "103.22.200.0/22",
        "103.31.4.0/22",
        "141.101.64.0/18",
        "108.162.192.0/18",
        "190.93.240.0/20",
        "188.114.96.0/20",
        "197.234.240.0/22",
        "198.41.128.0/17",
        "162.158.0.0/15",
        "104.16.0.0/12",
        "172.64.0.0/13",
        "131.0.72.0/22",
        "192.168.0.0/16",
        "127.0.0.0/8",
        "10.0.0.0/8",
        "172.16.0.0/12",
        "106.193.204.0/22"
        ]
      [http.middlewares.test-ipwhitelist.ipWhiteList.ipStrategy]
        depth = 2

